# Generated by Django 4.0.4 on 2022-06-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=30)),
                ('imagen', models.CharField(max_length=30)),
            ],
        ),
    ]
